name: nuaa
# 每天00:30打卡
on:
  push:
    branches: master
  schedule:
    - cron: '01 16 * * *'

jobs:
  save:
    name: save
    runs-on: ubuntu-latest
    steps:
    - name: save
      env:
        SCKEY: ${{ secrets.SCKEY }}
        KEY: ${{ secrets.KEY}}
      run: |
        git clone https://github.com/williamgoods/NUAA-Check .
        sudo apt-get install python-setuptools python3-setuptools
        pip3 install certifi==2021.10.8 \
        charset-normalizer==2.0.12 \
        idna==3.3 \
        pycryptodome==3.14.1 \
        requests==2.27.1 \
        urllib3==1.26.9 

        python3 main.py 
          
